#define VIAL_KEYBOARD_UID {0x0C, 0x83, 0xBB, 0x28, 0xFE, 0xFE, 0x51, 0x11}
#define VIAL_UNLOCK_COMBO_ROWS { 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0 }

// For via/vial only
#define DYNAMIC_KEYMAP_LAYER_COUNT 5